# Generated by Django 5.0.2 on 2026-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_grade', models.CharField(max_length=5)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('class_size', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('headteacher_comment', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-term__start_date', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('header_text', models.TextField(default='')),
                ('show_position', models.BooleanField(default=True)),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_behavior', models.BooleanField(default=False)),
                ('show_grade_scale', models.BooleanField(default=True)),
                ('grading_scale', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
            },
        ),
    ]
